trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm test
  displayName: 'Run tests'

- script: |
    mkdir $(Build.ArtifactStagingDirectory)/app
    cp app.js package.json $(Build.ArtifactStagingDirectory)/app
  displayName: 'Prepare artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: 'application'
  displayName: 'Publish artifact'